#! /usr/bin/env bash
# tmux, above is fake for colors

# session management
set -g detach-on-destroy off # switch to another session instead of detaching when closing last window
bind -n M-s new-session

# passthrough mode - disable all bindings to pass keys through to apps
unbind -a -Tpassthrough                         # clear passthrough table first
bind -Tpassthrough M-Escape set key-table root  # exit: set key table back to root
bind -n M-Escape set -g key-table passthrough   # enter: set key table to passthrough

# scrollback
set -g history-limit 50000

## rename window (disable auto-rename, unless input is empty)
bind -n M-R command-prompt -p "Window name:" {
    if -F "#{==:%%,}" {
        setw automatic-rename on
    } {
        rename-window "%%"
        setw automatic-rename off
    }
}

# window management
set -g renumber-windows on # keep numbers low
## cycle panes
bind -n M-h select-pane -t :.-
bind -n M-l select-pane -t :.+
## cycle windows
bind -n M-j previous-window
bind -n M-k next-window
## swap windows
bind -n M-J swap-window -t -1 -d
bind -n M-K swap-window -t +1 -d
bind -n M-m choose-tree -s "move-window -t '%%'"
## interactive window search
bind -n M-w choose-tree -Zw
## new window
bind -n M-c new-window -a -c "#{pane_current_path}"
bind -n M-q confirm-before -p "kill-pane #P? (y/n)" kill-pane

# clipboarding
bind -n M-e run-shell "
tmp=$(mktemp /tmp/tmux_XXXXXX.log)
tmux capture-pane -pJS - | tac | awk 'NF{p=1} p' | tac > \$tmp
tmux display-popup -E -y 0 -x 0 -w 100% -h 100% \"$EDITOR \$tmp +999999
rm \$tmp\""


# configuration reload
bind -n M-r source-file ~/.config/tmux/tmux.conf

