# dynhetz: a Hetzner AX102-class dedicated server. AMD Ryzen 7 7700 (8C/16T),
# 64 GiB DDR5-5600, two 1 TB Samsung PM9A1 NVMe drives in a mirror -- see
# ./disko.nix.
#
# Structured like ../hetztop, which is a cloud VM, with the differences a
# physical machine forces:
#
#  - systemd-boot on an EFI System Partition, not BIOS grub on a QEMU disk.
#  - The qemu-guest profile is gone; AMD microcode and redistributable
#    firmware are in its place.
#  - Static networking, because Hetzner routes a dedicated server rather than
#    leasing it an address: the IPv4 gateway sits *outside* our /26 and needs
#    an explicit host route before the default route can resolve, and IPv6
#    hangs off the link-local gateway.
#  - `usePredictableInterfaceNames = false`, so the NIC is `eth0` here exactly
#    as it was in the rescue system the machine was probed from.
{
  pkgs,
  lib,
  modulesPath,
  inputs,
  homeArgs,
  ...
}:
{
  imports = [
    inputs.disko.nixosModules.disko
    inputs.home-manager.nixosModules.home-manager
    ./disko.nix
    ./boot-mirror.nix
    ./initrd-ssh.nix
    ./installscript.nix
    ./podman.nix
    ./ollama.nix
    ./ttyd.nix
    # pynixd moved into the nanopynix monorepo, so its NixOS module comes from
    # that input rather than a checkout of its own. nanopynix is `flake = false`,
    # so this is the source tree and no second flake is evaluated.
    "${inputs.nanopynix}/pynixd/nix/nixos"
    ./pynixd.nix
    ./ai-rebuild.nix
    ./btrfs.nix
    ./nix-gc.nix
    ./terminfo.nix
    ./mdmonitor-mail.nix
    ../../secrets
  ];
  config = {
    # The account and the home-manager wiring used to live in ../home, next to
    # the modules it pulls in. It is host state -- a password hash, a uid, the
    # groups this machine has -- so it belongs to the host now that ../../home
    # is shared with the MacBook and ChromeOS.
    programs.fish.enable = true;
    users.users.lillecarl = {
      extraGroups = [
        "wheel"
        "podman"
      ];
      hashedPassword = "$y$j9T$U4zBBS9RMV9YMttHauO8k0$V.KT/P/AdBTXXT8f6p9EIlCsZV5UnaPDgEVtUvUJU3C";
      isNormalUser = true;
      openssh.authorizedKeys.keyFiles = [ ../../lillecarl.pub ];
      shell = pkgs.fish;
    };
    home-manager = {
      useGlobalPkgs = true;
      extraSpecialArgs = homeArgs;
      users.lillecarl = import ./home.nix;
    };

    boot.loader.systemd-boot.enable = true;
    # Each ESP (nvme0's and, mirrored, nvme1's -- ./boot-mirror.nix) is 1 GiB.
    # With no limit, systemd-boot keeps one entry per generation forever;
    # kernels/initrds are content-addressed so they don't grow with that, but
    # the .conf files and any generation that pins an unshared kernel do. 10
    # bounds it well under the partition.
    boot.loader.systemd-boot.configurationLimit = 10;
    boot.loader.efi.canTouchEfiVariables = true;
    # Generated by running nixos-generate-config on the machine itself -- the
    # rescue system has nix, so the tool was built there against the same
    # channel pin this repo uses and run with --show-hardware-config:
    #
    #   boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" ];
    #   boot.kernelModules = [ "kvm-amd" ];
    #
    # ahci is loaded on the board despite there being no SATA disks; kvm-amd
    # is the Ryzen's virtualization module, wanted before anything asks for
    # it. igb is added beside them: the I210 NIC that eth0 depends on, named
    # explicitly rather than left to autoload.
    boot.initrd.availableKernelModules = [
      "nvme"
      "xhci_pci"
      "ahci"
      # ../initrd-ssh.nix brings up eth0 inside the initrd itself, before
      # switch-root -- the driver has to already be in the initrd's own
      # module set for that, not just the post-switch-root system's.
      "igb"
    ];
    boot.kernelModules = [
      "igb"
      "kvm-amd"
    ];
    boot.kernelPackages = pkgs.linuxPackages_latest;

    # A physical CPU ships microcode revisions the board's firmware may not
    # carry; load ours from nixpkgs at initrd time.
    hardware.cpu.amd.updateMicrocode = true;
    hardware.enableRedistributableFirmware = true;

    # Support building crossPlatform with QEMU
    boot.binfmt.emulatedSystems = [
      {
        "x86_64-linux" = "aarch64-linux";
        "aarch64-linux" = "x86_64-linux";
      }
      .${pkgs.stdenv.hostPlatform.system}
    ];
    time.timeZone = "Europe/Stockholm";
    # Terminfo packages for terminals we're using
    environment.systemPackages = with pkgs.pkgsBuildBuild; [
      foot.terminfo
    ];
    # reference catppuccin whiskers so it doesn't get garbage collected every time you collect garbage.
    environment.etc.catppucin-whiskers.source =
      inputs.catppuccin.packages.${pkgs.stdenv.hostPlatform.system}.whiskers;
    networking.hostName = "dynhetz";
    networking.usePredictableInterfaceNames = false;
    networking.useDHCP = false;
    # Moved from scripted networking (networking.interfaces.eth0 +
    # networking.defaultGateway{,6}) to networkd, so this host's main
    # networking backend matches its own initrd's (../initrd-ssh.nix's
    # boot.initrd.systemd.network.networks."10-eth0" -- systemd's initrd is
    # networkd-only regardless of what the real system uses, so that alone
    # was never a reason to switch this too). The addresses, routes and the
    # on-link quirk below are copied from that file verbatim: same NIC, same
    # subnet, same gateway, already verified working on the real machine
    # there. See its own comment for why GatewayOnLink is needed for IPv4
    # but not IPv6.
    networking.useNetworkd = true;
    systemd.network.networks."10-eth0" = {
      matchConfig.Name = "eth0";
      address = [
        "37.27.129.237/26"
        "2a01:4f9:3071:11d7::2/64"
      ];
      routes = [
        {
          Gateway = "37.27.129.193";
          GatewayOnLink = true;
        }
        {
          Gateway = "fe80::1";
        }
      ];
      networkConfig.DHCP = "no";
    };
    networking.nameservers = [
      "185.12.64.1"
      "185.12.64.2"
      "2a01:4ff:ff00::add:1"
      "2a01:4ff:ff00::add:2"
    ];
    environment.etc.nixpkgs.source = inputs.nixpkgs.outPath;
    programs.bash.shellInit = lib.mkBefore ''
      if [ -n "$CLAUDECODE" ]; then
        eval "$(DIRENV_LOG_FORMAT= ${lib.getExe pkgs.direnv} hook bash)"
        unset HTTPS_PROXY
      fi
    '';
    nix = {
      settings = {
        trusted-users = [ "lillecarl" ];
        experimental-features = [
          "nix-command"
          "flakes"
          "read-only-local-store"
          "ca-derivations"
          "dynamic-derivations"
          "recursive-nix"
        ];
        trusted-public-keys = [
          "hydra.nixos.org-1:CNHJZBh9K4tP3EKF6FkkgeVYsS3ohTl+oS0Qa8bezVs="
          "nix-csi.cachix.org-1:i4w33gR4efO67jpz8U7g/MdvRQ6mQ3LEF9fB8tES60g="
          "lillecarl.cachix.org-1:NN/LLMg7mbyvZCu32Qlo8LpSHqNw7Rr3VBCEYQvRpT0="
        ];
        substituters = [
          "https://nix-csi.cachix.org"
          "https://lillecarl.cachix.org"
        ];
        sandbox = "relaxed";
      };
      nixPath = [
        "nixpkgs=/etc/nixpkgs"
      ];
      registry = {
        nixpkgs.flake = inputs.nixpkgs;
        n.flake = inputs.nixpkgs;
      };
    };
    services.btrfs.autoScrub = {
      enable = true;
      interval = "monthly";
    };

    programs.mosh = {
      enable = true;
      openFirewall = true;
    };
    services.openssh = {
      enable = true;
      openFirewall = true;
    };
    system.stateVersion = "25.11";
  };
}
