# dynhetz: a Hetzner AX102-class dedicated server. AMD Ryzen 7 7700 (8C/16T),
# 64 GiB DDR5-5600, two 1 TB Samsung PM9A1 NVMe drives in a mirror -- see
# ./disko.nix.
#
# Structured like ../hetztop, which is a cloud VM, with the differences a
# physical machine forces:
#
#  - systemd-boot on an EFI System Partition, not BIOS grub on a QEMU disk.
#  - The qemu-guest profile is gone; AMD microcode and redistributable
#    firmware are in its place.
#  - Static networking, because Hetzner routes a dedicated server rather than
#    leasing it an address: the IPv4 gateway sits *outside* our /26 and needs
#    an explicit host route before the default route can resolve, and IPv6
#    hangs off the link-local gateway.
#  - `usePredictableInterfaceNames = false`, so the NIC is `eth0` here exactly
#    as it was in the rescue system the machine was probed from.
{ config
, pkgs
, lib
, modulesPath
, inputs
, homeArgs
, ...
}:
{
  imports = [
    inputs.disko.nixosModules.disko
    inputs.home-manager.nixosModules.home-manager
    ./disko.nix
    ./boot-mirror.nix
    ./initrd-ssh.nix
    ./installscript.nix
    ./podman.nix
    ./kubernetes
    ./nat64.nix
    ./wireguard.nix
    ./scan-access.nix
    ./ollama.nix
    ./ttyd.nix
    # pynixd stays on its own umbrella pin, `nixidae-pynixd` -- see
    # ../flake.nix. That input never names a path in ./overrides.nix, so a
    # local checkout moves nothing here and a rebuild restarts no daemon
    # unless the lock itself moved. `.sources` reads the lock and needs no
    # package set, which is what keeps it safe to name here in `imports`.
    ((import inputs.nixidae-pynixd { }).sources.pynixd + "/nix/nixos")
    ./pynixd.nix
    ./ai-rebuild.nix
    ./btrfs.nix
    ./nix-gc.nix
    ./terminfo.nix
    ./pipewire.nix
    ./xdg-user-dirs.nix
    ./mdmonitor-mail.nix
    ./dynusers.nix
    ../../secrets
  ];
  config = {
    # The account and the home-manager wiring used to live in ../home, next to
    # the modules it pulls in. It is host state -- a password hash, a uid, the
    # groups this machine has -- so it belongs to the host now that ../../home
    # is shared with the MacBook and ChromeOS.
    programs.fish.enable = true;
    users.users.lillecarl = {
      # frrvty is what `vtysh` needs, and the only thing it needs: the daemons
      # listen on /run/frr/*.vty, which are srwxrwx--- frr:frrvty, while
      # /run/frr itself is world-traversable. Without it vtysh reaches no
      # daemon at all and says to try a privileged user, so every look at the
      # BGP session with a guest cluster costs a password.
      #
      # It is not read-only access. A member of frrvty can `configure
      # terminal` and change this host's routing for as long as FRR runs --
      # what it cannot do is write ./kubernetes/guest-routing.nix, so the next
      # restart takes the configuration back. Granted deliberately, on the
      # same reasoning as wheel above.
      #
      # Conditional on the daemon, because a group that no service creates is
      # an activation failure rather than a missing capability.
      extraGroups = [
        "wheel"
        "podman"
      ]
      ++ lib.optional config.services.frr.bgpd.enable "frrvty";
      hashedPassword = "$y$j9T$U4zBBS9RMV9YMttHauO8k0$V.KT/P/AdBTXXT8f6p9EIlCsZV5UnaPDgEVtUvUJU3C";
      isNormalUser = true;
      openssh.authorizedKeys.keyFiles = [ ../../lillecarl.pub ];
      shell = pkgs.fish;
      # Without this the user manager -- and the aid and ocahub user
      # services with it -- stops at the last logout. The daemons must
      # survive a reboot nobody logs into afterwards.
      linger = true;
    };
    home-manager = {
      useGlobalPkgs = true;
      extraSpecialArgs = homeArgs;
      users.lillecarl = import ./home.nix;
      # Move aside any unmanaged file home-manager is about to replace,
      # instead of failing activation on it. The collision this covers:
      # xdg-user-dirs-update (./xdg-user-dirs.nix) writes
      # ~/.config/user-dirs.dirs before home-manager links its own
      # managed copy on the same switch.
      backupFileExtension = "hm-backup";
    };

    boot.loader.systemd-boot.enable = true;
    # Each ESP (nvme0's and, mirrored, nvme1's -- ./boot-mirror.nix) is 1 GiB.
    # With no limit, systemd-boot keeps one entry per generation forever;
    # kernels/initrds are content-addressed so they don't grow with that, but
    # the .conf files and any generation that pins an unshared kernel do. 10
    # bounds it well under the partition.
    boot.loader.systemd-boot.configurationLimit = 10;
    boot.loader.efi.canTouchEfiVariables = true;
    # Generated by running nixos-generate-config on the machine itself -- the
    # rescue system has nix, so the tool was built there against the same
    # channel pin this repo uses and run with --show-hardware-config:
    #
    #   boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" ];
    #   boot.kernelModules = [ "kvm-amd" ];
    #
    # ahci is loaded on the board despite there being no SATA disks; kvm-amd
    # is the Ryzen's virtualization module, wanted before anything asks for
    # it. igb is added beside them: the I210 NIC that eth0 depends on, named
    # explicitly rather than left to autoload.
    boot.initrd.availableKernelModules = [
      "nvme"
      "xhci_pci"
      "ahci"
      # ../initrd-ssh.nix brings up eth0 inside the initrd itself, before
      # switch-root -- the driver has to already be in the initrd's own
      # module set for that, not just the post-switch-root system's.
      "igb"
    ];
    boot.kernelModules = [
      "igb"
      "kvm-amd"
    ];
    boot.kernelPackages = pkgs.linuxPackages_latest;
    boot.kernel.sysctl."kernel.task_delayacct" = 1;

    # A physical CPU ships microcode revisions the board's firmware may not
    # carry; load ours from nixpkgs at initrd time.
    hardware.cpu.amd.updateMicrocode = true;
    hardware.enableRedistributableFirmware = true;

    # Memory is this host's scarce resource (61 GiB backing five KubeVirt
    # guests plus the host cluster); CPU is not. So hugepages stay off and
    # identical pages merge across VMs:
    # - transparent_hugepage=never on the cmdline (future boots) and via
    #   tmpfiles at each switch (right now, no reboot): 2 MiB pages never
    #   merge, and nothing here wants them.
    # - hardware.ksm merges identical 4 KiB pages across the five
    #   same-image guests, no guest change needed.
    boot.kernelParams = [ "transparent_hugepage=never" ];
    systemd.tmpfiles.rules = [
      "w /sys/kernel/mm/transparent_hugepage/enabled - - - - never"
    ];
    hardware.ksm.enable = true;

    # Support building crossPlatform with QEMU
    boot.binfmt.emulatedSystems = [
      {
        "x86_64-linux" = "aarch64-linux";
        "aarch64-linux" = "x86_64-linux";
      }.${pkgs.stdenv.hostPlatform.system}
    ];
    time.timeZone = "Europe/Stockholm";
    # Terminfo packages for terminals we're using
    environment.systemPackages = with pkgs.pkgsBuildBuild; [
      foot.terminfo
    ];
    # reference catppuccin whiskers so it doesn't get garbage collected every time you collect garbage.
    environment.etc.catppucin-whiskers.source =
      inputs.catppuccin.packages.${pkgs.stdenv.hostPlatform.system}.whiskers;
    networking.hostName = "dynhetz";
    networking.usePredictableInterfaceNames = false;
    networking.useDHCP = false;
    # Moved from scripted networking (networking.interfaces.eth0 +
    # networking.defaultGateway{,6}) to networkd, so this host's main
    # networking backend matches its own initrd's (../initrd-ssh.nix's
    # boot.initrd.systemd.network.networks."10-eth0" -- systemd's initrd is
    # networkd-only regardless of what the real system uses, so that alone
    # was never a reason to switch this too). The addresses, routes and the
    # on-link quirk below are copied from that file verbatim: same NIC, same
    # subnet, same gateway, already verified working on the real machine
    # there. See its own comment for why GatewayOnLink is needed for IPv4
    # but not IPv6.
    networking.useNetworkd = true;
    systemd.network.networks."10-eth0" = {
      matchConfig.Name = "eth0";
      address = [
        "37.27.129.237/26"
        "2a01:4f9:3071:11d7::2/64"
      ];
      routes = [
        {
          Gateway = "37.27.129.193";
          GatewayOnLink = true;
        }
        {
          Gateway = "fe80::1";
        }
      ];
      networkConfig.DHCP = "no";
    };
    networking.nameservers = [
      "185.12.64.1"
      "185.12.64.2"
      "2a01:4ff:ff00::add:1"
      "2a01:4ff:ff00::add:2"
    ];
    environment.etc.nixpkgs.source = inputs.nixpkgs.outPath;
    environment.etc.home-manager.source = inputs.home-manager.outPath;
    programs.bash.shellInit = lib.mkBefore ''
      if [ -n "$CLAUDECODE" ]; then
        eval "$(DIRENV_LOG_FORMAT= ${lib.getExe pkgs.direnv} hook bash)"
        unset HTTPS_PROXY
      fi
    '';
    nix = {
      settings = {
        trusted-users = [ "lillecarl" ];
        experimental-features = [
          "nix-command"
          "flakes"
          "read-only-local-store"
          "ca-derivations"
          "dynamic-derivations"
          "recursive-nix"
          "auto-allocate-uids"
          "cgroups"
        ];
        # `uid-range`: a build gets 65536 ids and a cgroup of its own, which
        # systemd as PID 1 in a container needs. user-mode-nixos' sandboxed
        # container guests and nixpkgs' nspawn tests ask for it.
        auto-allocate-uids = true;
        use-cgroups = true;
        # Replaces the default list, so it names the defaults too.
        system-features = [
          "nixos-test"
          "benchmark"
          "big-parallel"
          "kvm"
          "uid-range"
        ];
        trusted-public-keys = [
          "hydra.nixos.org-1:CNHJZBh9K4tP3EKF6FkkgeVYsS3ohTl+oS0Qa8bezVs="
          "lillecarl.cachix.org-1:NN/LLMg7mbyvZCu32Qlo8LpSHqNw7Rr3VBCEYQvRpT0="
          "nixkube.cachix.org-1:H8UE0jlI9pxHexK/NhDmEoLDarJXp1WTymQrsajlh7M="
          "ctrl-os:baPzGxj33zp/P+GAIJXsr8ss9Law+qEEFViX1+flbv8="
          "kubernetes4nix.cachix.org-1:8VVvvphJTNShbEwmgz99GiUTVaZB/CYB9hWQBzzFD0w="
        ];
        # nixkube: pynixd refuses an unsigned path from the untrusted push
        # user, so a nixkube built here fails solid-kubernetes' kubeapply.
        # cyberus-linux: solid-kubernetes' nixlab3 nodes run Cyberus Linux,
        # with Kubernetes from kubernetes4nix.
        substituters = [
          # pynixd's own HTTP cache first: it races every upstream at once
          # and redirects the NAR to the highest-priority one that answered,
          # where Nix itself would ask each in turn for every path. Misses
          # fall through to the next substituter, so this entry only ever
          # accelerates. ../../pynixd.nix sets the port.
          "http://127.0.0.1:8080"
          "https://lillecarl.cachix.org"
          "https://nixkube.cachix.org"
          "https://cache.cyberus-linux.com"
          "https://kubernetes4nix.cachix.org"
        ];
        sandbox = "relaxed";
      };
      nixPath = [
        "nixpkgs=/etc/nixpkgs"
        "home-manager=/etc/home-manager"
      ];
      registry = {
        nixpkgs.flake = inputs.nixpkgs;
        n.flake = inputs.nixpkgs;
      };
    };
    services.btrfs.autoScrub = {
      enable = true;
      interval = "monthly";
    };
    # Weekly discard: btrfs mounts without discard=async, so nothing trims
    # until this runs. The block layer already discards (see ./disko.nix).
    services.fstrim.enable = true;

    programs.mosh = {
      enable = true;
      openFirewall = true;
    };
    services.openssh = {
      enable = true;
      openFirewall = true;
      settings = {
        # What pymux asks of this sshd when a client attaches over
        # `ssh://`. All three are openssh's own defaults, so this
        # changes nothing today. They are written down because a later
        # hardening pass that turns one off breaks pymux quietly:
        # forwarding stops and the only symptom is a dead port.
        #
        # `AllowStreamLocalForwarding` is the one to keep. The client
        # reaches the pymux server's unix socket over
        # `direct-streamlocal@openssh.com`, so turning it off does not
        # cost a feature -- it stops a remote attach working at all.
        AllowTcpForwarding = true;
        AllowStreamLocalForwarding = true;
        # A remote forward binds loopback here, whatever the client
        # asked for. That suits what `-R` is for: reaching a service on
        # the laptop, such as Chrome's CDP port, from a pane on this
        # machine. `clientspecified` is what would let a client publish
        # a port on this machine's network, and it is not wanted.
        GatewayPorts = "no";
        # Notice a client that stopped answering, after about 45
        # seconds. sshd never asks by default, so a laptop that sleeps
        # leaves its session here for as long as the kernel keeps the
        # dead TCP connection -- and pymux drops a client only when its
        # socket closes, so the sleeping laptop stays attached to the
        # session and its stale terminal size keeps constraining the
        # window. Lillecarl/pymux#446.
        #
        # **It applies to every session on this machine, not only
        # pymux's.** Any response resets the count, so a link that is
        # merely slow survives; a link with 45 seconds of complete
        # silence is dropped.
        ClientAliveInterval = 15;
        ClientAliveCountMax = 3;
      };
    };
    system.stateVersion = "25.11";
  };
}
