# The fingerprints of the two OpenPGP keys in this directory.
#
# Generated by ./pgp-create. Do not edit: it rewrites this file whole.
#
# Committed, because ../home/gpg.nix and ../home/vcs.nix read it at evaluation
# time and a fresh clone has to find it. Nothing secret is here -- a
# fingerprint is the public name of a key.
{
  # Carl Andersson <carl.andersson@dynamist.se>
  work = "C7579F6E2A5C01D390635F2633FA7BA23355CACE";

  # lillecarl <prettygood@lillecarl.com>
  personal = "0DAE2F9A57182ABDE472189640BF05D0FE7ACB19";
}
